import pyautogui as pag
import pyperclip as ppc
import time
pag.PAUSE = 0.5
pag.press("Win")
pag.write("Infosis")
time.sleep(3)
pag.press("Enter")
time.sleep(10)
pag.write("jean")
pag.press("Enter")
pag.write("0409")
pag.press("Enter")
time.sleep(5)
pag.click(802, 80)
time.sleep(10)
pag.click(496, 41)
pag.write("9")
pag.press("Enter")
time.sleep(6)
pag.press("TAB")
pag.press("TAB")
ppc.copy("08/03/2022")
pag.hotkey("ctrl", "v")
pag.press("TAB")
ppc.copy("08/03/2022")
pag.hotkey("ctrl", "v")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.write("145")
pag.press("Enter")
pag.write("116")
pag.press("Enter")
pag.write("226")
pag.press("Enter")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
pag.press("TAB")
time.sleep(1)
pag.press("UP")
pag.press("UP")
pag.press("UP")
pag.press("UP")
pag.press("UP")
pag.press("UP")
pag.press("UP")
pag.press("UP")
pag.press("space")

pag.click(886, 677)
